version: '3'
services:
    web:
        container_name: app
        build: .
        ports:
            - 9091:80
        volumes:
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
        environment:
            TZ: "IST"
        networks:
            - localnet
   
networks:
  localnet:
    driver: bridge